services:
  pypowerwall:
      image: sbmanhome/powerwall3mqtt_hacore
      container_name: powerwall3mqtt
      hostname: pypowerwall3mqtt
      restart: unless-stopped
      environment:
        - POWERWALL3MQTT_CONFIG_LOG_LEVEL=warning
        - POWERWALL3MQTT_CONFIG_TEDAPI_HOST=192.168.91.1
        - POWERWALL3MQTT_CONFIG_TEDAPI_PASSWORD=YOURPASSWORD
        - POWERWALL3MQTT_CONFIG_TEDAPI_POLL_INTERVAL=30
        - POWERWALL3MQTT_CONFIG_TEDAPI_REPORT_VITALS=False
        - POWERWALL3MQTT_CONFIG_MQTT_BASE_TOPIC=homeassistant
        - POWERWALL3MQTT_CONFIG_MQTT_HOST=YOURMQTTHOSTIP
        - POWERWALL3MQTT_CONFIG_MQTT_PORT=1883
        - POWERWALL3MQTT_CONFIG_MQTT_VERIFY_TLS=False
        - POWERWALL3MQTT_CONFIG_MQTT_SSL=False
#        - POWERWALL3MQTT_CONFIG_MQTT_USERNAME=YOURMQTTUSERNAME
#        - POWERWALL3MQTT_CONFIG_MQTT_PASSWORD=YOURMQTTPASSWORD
#        - POWERWALL3MQTT_CONFIG_MQTT_CA=CAASNEEDED
#        - POWERWALL3MQTT_CONFIG_MQTT_CERT=CERTASNEEDED
#        - POWERWALL3MQTT_CONFIG_MQTT_KEY=KEYASNEEDED
